---
- hosts: node
  become: yes
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: true
      cache_valid_time: 3600
      force_apt_get: true
  - name: Install software-properties-common
    apt:
      name: software-properties-common
      state: present
      update_cache: yes   
  - name: install JRE
    apt:
      name: default-jre
      state: present
  - name: "Add jenkins key"
    apt_key:
     url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
     state: present
  - name: "Install Jenkins"
    apt:
      update_cache: yes
      state: present
  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started



